[package]
name = "updater"
version = "0.0.0"
edition = "2021"
rust-version = "1.57"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.27.0",  features = ["full"] }
regex = "1.7.3"
